//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceStationSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceStationSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;DockId&quot;:1,&quot;DualEnvironment&quot;:false,&quot;CurrentEnvironment&quot;:&quot;O&quot;,&quot;SupportsHuman&quot;:true,&quot;SupportsAqua&quot;:false, &quot;SupportsMega&quot;:false,&quot;ClassMin&quot;:1,&quot;ClassMax&quot;:4},
        ///{&quot;DockId&quot;:2,&quot;DualEnvironment&quot;:false,&quot;CurrentEnvironment&quot;:&quot;O&quot;,&quot;SupportsHuman&quot;:true,&quot;SupportsAqua&quot;:false,&quot;SupportsMega&quot;:false,&quot;ClassMin&quot;:1,&quot;ClassMax&quot;:4},
        ///{&quot;DockId&quot;:3,&quot;DualEnvironment&quot;:false,&quot;CurrentEnvironment&quot;:&quot;O&quot;,&quot;SupportsHuman&quot;:true,&quot;SupportsAqua&quot;:false,&quot;SupportsMega&quot;:true,&quot;ClassMin&quot;:1,&quot;ClassMax&quot;:7},
        ///{&quot;DockId&quot;:4,&quot;DualEnvironment&quot;:false,&quot;CurrentEnvironm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Docks2019_json {
            get {
                return ResourceManager.GetString("Docks2019.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ShipClassId&quot;:1,&quot;ShipName&quot;:&quot;Tyrant&quot;,&quot;ShipFedId&quot;:1000,&quot;CaptainName&quot;:&quot;Brian Aldiss&quot;,&quot;FuelCapacity&quot;:100,&quot;FuelOnBoard&quot;:90,&quot;CargoToUnload&quot;:100,&quot;WasteCapacity&quot;:100,&quot;CurrentWaste&quot;:55,&quot;Docked&quot;:false,&quot;RepairCode&quot;:4,&quot;FoodCode&quot;:1,&quot;CurrentPower&quot;:23,&quot;Race&quot;:&quot;Human&quot;,&quot;CargoToLoad&quot;:149},{&quot;ShipClassId&quot;:2,&quot;ShipName&quot;:&quot;Triumph&quot;,&quot;ShipFedId&quot;:1001,&quot;CaptainName&quot;:&quot;R.M. Meluch&quot;,&quot;FuelCapacity&quot;:200,&quot;FuelOnBoard&quot;:180,&quot;CargoToUnload&quot;:200,&quot;WasteCapacity&quot;:200,&quot;CurrentWaste&quot;:110,&quot;Docked&quot;:false,&quot;RepairCode&quot;:5,&quot;FoodCode&quot;:0,&quot;CurrentPower&quot;:13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinalShips2019_json {
            get {
                return ResourceManager.GetString("FinalShips2019.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;1&quot;:&quot;Runabout&quot;,&quot;2&quot;:&quot;Personal&quot;,&quot;3&quot;:&quot;Skeeter&quot;,&quot;4&quot;:&quot;Small Shuttle&quot;,&quot;5&quot;:&quot;Medium Shuttle&quot;,&quot;6&quot;:&quot;Large Shuttle&quot;,&quot;7&quot;:&quot;Personnel Transport&quot;,&quot;8&quot;:&quot;Cargo Transport&quot;,&quot;9&quot;:&quot;Cargo Transport II&quot;,&quot;10&quot;:&quot;Scout Ship&quot;,&quot;11&quot;:&quot;Explorer&quot;,&quot;12&quot;:&quot;Dreadnaught&quot;}
        ///.
        /// </summary>
        internal static string ShipClasses_json {
            get {
                return ResourceManager.GetString("ShipClasses.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1405
        ///1056
        ///1062
        ///1449
        ///1107
        ///1443
        ///1192
        ///1008
        ///1116
        ///1408
        ///1437
        ///1103
        ///1186
        ///1013
        ///1195
        ///1110
        ///1567
        ///1321
        ///1017
        ///1414
        ///1227
        ///1334
        ///1545
        ///1469
        ///1136
        ///1057
        ///1085
        ///1518
        ///1061
        ///1397
        ///1347
        ///1146
        ///1511
        ///1535
        ///1438
        ///1573
        ///1152
        ///1117
        ///1403
        ///1044
        ///1153
        ///1349
        ///1087
        ///1371
        ///1273
        ///1322
        ///1395
        ///1141
        ///1450
        ///1417
        ///1480
        ///1177
        ///1296
        ///1297
        ///1512
        ///1071
        ///1088
        ///1170
        ///1313
        ///1049
        ///1357
        ///1250
        ///1523
        ///1295
        ///1060
        ///1291
        ///1167
        ///1228
        ///1151
        ///1198
        ///1534
        ///1451
        ///1494
        ///1548
        ///1261
        ///1453
        ///1246
        ///1173
        ///1196
        ///1389
        ///1238
        ///1519
        ///1067
        ///1219
        ///1493
        ///11 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShipQueue2019 {
            get {
                return ResourceManager.GetString("ShipQueue2019", resourceCulture);
            }
        }
    }
}
